openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0

paths:
  /api/users:
    get:
      summary: My first API test
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
                  message2:
                    type: number
                    example: 10000
  
      responses:
        '201':
          description: Created
  








servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
      
